// JavaScript file for the Scientific Calculator Project

// Using DOM methods to select the HTML elements
var screen_display = document.querySelector("#screen_display");
var btns = document.querySelectorAll(".btn");
var total_mrc = [];
var final_mrc_sum = 0;

// Looping through the NodeList generated by the DOM methods and applying EventListener to them.
for (let items of btns){
    items.addEventListener("click", function(){
        btntext = items.innerText;

        if (btntext == "x"){
            btntext = '*';
        }

        screen_display.value += btntext;
    });
}

// Function for clearing the Display Area
function allClear()
{
    screen_display.value = '';
}

// Function for displaying value of pi
function pi(){
    screen_display.value = 3.14159265359;
}

// Function for displaying the value of 'e'
function e(){
    screen_display.value = 2.71828182846;
}

// Function for storing numbers into memory as a positive value
function m_plus(){
    total_mrc.push(+screen_display.value);
    allClear();
}

// Function for storing numbers into memory as a negative value
function m_minus(){
    total_mrc.push(-screen_display.value);
    allClear();
}

// Function for calculating the final output of the numbers in the memory
function final_mrc_calculation(){
    for (let i=0; i<total_mrc.length; i++){
        final_mrc_sum += total_mrc[i];
    }
    screen_display.value = final_mrc_sum;
    total_mrc = 0;
    final_mrc_sum = 0;
}

// Function for clearing the memory space.
function m_clear(){
    allClear();
    total_mrc = 0;
    console.log(total_mrc);
}

// Function for calculating the sin of the value
function sin(){
    screen_display.value = Math.sin(screen_display.value);
}

// Function for deleting value one by one
function backspace(){
    screen_display.value = screen_display.value.substr(0, screen_display.value.length-1);
}

// Function for calculating the square of the number
function squares(){
    screen_display.value = Math.pow(screen_display.value,2);
}

// Function for calculating the inverse of the number
function inverse(){
    screen_display.value = 1 / screen_display.value;
}

// Function for calculating the absolute value of the number
function absolute(){
    screen_display.value = Math.abs(screen_display.value);
}

// Function for calculating the cos of the number
function cos(){
    screen_display.value = Math.cos(screen_display.value);
}

// Function for calculating the tan of the number.
function tan(){
    screen_display.value = Math.tan(screen_display.value);
}

// Function for calculating the square root of the number
function squareRoot(){
    screen_display.value = Math.sqrt(screen_display.value);
}

// Function for calculating the calculating the factorial of the number
function factorial(){
    var num, fact;
    fact = 1;
    num = screen_display.value;

    for (let i=1; i<=num; i++){
        fact = fact * i;
    }
    screen_display.value = fact;
}

// Function for calculating the power of the number
function power(){
    screen_display.value = Math.pow(screen_display.value, 2);
}

// Function for calculating the number when raised to power of 10
function raiseToTen(){
    screen_display.value = Math.pow(10,screen_display.value);
}

// Function for calculating the logarithm of the number
function logarithm(){
    screen_display.value = Math.log10(screen_display.value);
}

// Function for calculating the natural log of the number
function naturalLog(){
    screen_display.value = Math.log(screen_display.value);
}

// Function for calculating the total of the equation
function equals(){
    screen_display.value=eval(screen_display.value);
}

